INSERT INTO students (name) VALUES ("Vivian Shangxuan Zhang");
INSERT INTO students (name) VALUES ("Ivan Brennan");
INSERT INTO students (name) VALUES ("Kyle Shike");
INSERT INTO students (name) VALUES ("Michael Polycarpou");
INSERT INTO students (name) VALUES ("Student Name");
INSERT INTO students (name) VALUES ("David Bella");
INSERT INTO students (name) VALUES ("Greg Eng");
INSERT INTO students (name) VALUES ("Mike Spangler");
INSERT INTO students (name) VALUES ("Emily Xie");
INSERT INTO students (name) VALUES ("Matt Campbell");
INSERT INTO students (name) VALUES ("Tiffany Peón");
INSERT INTO students (name) VALUES ("Alex Chiu");
INSERT INTO students (name) VALUES ("Amanda Himmelstoss");
INSERT INTO students (name) VALUES ("Christopher Lee");
INSERT INTO students (name) VALUES ("Daniel Chang");
INSERT INTO students (name) VALUES ("Ian Miller");
INSERT INTO students (name) VALUES ("Iris Lee");
INSERT INTO students (name) VALUES ("James Tong");
INSERT INTO students (name) VALUES ("Joe O'Conor");
INSERT INTO students (name) VALUES ("Jeanne Roniger");
INSERT INTO students (name) VALUES ("John Richardson");
INSERT INTO students (name) VALUES ("Josh Scaglione");
INSERT INTO students (name) VALUES ("Logan Hasson");
INSERT INTO students (name) VALUES ("Margaret Lee");
INSERT INTO students (name) VALUES ("");
INSERT INTO students (name) VALUES ("Sam Owens");
INSERT INTO students (name) VALUES ("Scott Luptowski");
INSERT INTO students (name) VALUES ("Sonja Hall");
INSERT INTO students (name) VALUES ("Theo Vora");
INSERT INTO students (name) VALUES ("Trevor McKendrick");
INSERT INTO students (name) VALUES ("Vinney Cavallo");
INSERT INTO students (name) VALUES ("Patrick Janson");
INSERT INTO students (name) VALUES ("Edina Vath");
-- UPDATE students SET quote = "It is the age of Data Mining. Embrace it with all heart." -- Vivian Zhang Said this. WHERE id = 1;
-- UPDATE students SET quote = "Quote It was the best of times it was meh." -- someone smart said this. WHERE id = 2;
-- UPDATE students SET quote =  WHERE id = 3;
-- UPDATE students SET quote = "Quote It was the best of times it was meh." -- someone smart said this. WHERE id = 4;
-- UPDATE students SET quote = "Don't be an idiot." - the Office WHERE id = 5;
-- UPDATE students SET quote = "Well, Mr. Frankel, who started the program, began to suffer from the computer disease that anybody who works with computers now knows about. It's a very serious disease and it interferes completely with the work. The trouble with computers is you play with them. They are so wonderful." -- Richard Feynman WHERE id = 6;
-- UPDATE students SET quote = "Go forth and set the world on fire." -- St. Ignatius of Loyola WHERE id = 7;
-- UPDATE students SET quote = "There is no Dana.  There is only Zuul." WHERE id = 8;
-- UPDATE students SET quote = "Stay hungry, stay foolish." -- Steve Jobs. WHERE id = 9;
-- UPDATE students SET quote = "People, when they are under surveillance, are already imprisoned." -- Jacob Applebaum (@ioerror) WHERE id = 10;
-- UPDATE students SET quote = "Nobody who ever gave his best regretted it." -- George Halas WHERE id = 11;
-- UPDATE students SET quote = "Anything is possible it is the beauty of living!!" -- Alex Chiu. WHERE id = 12;
-- UPDATE students SET quote =  WHERE id = 13;
-- UPDATE students SET quote = "If you don’t love something, you’re not going to go the extra mile, work the extra weekend, challenge the status quo as much." -- Steve Jobs WHERE id = 14;
-- UPDATE students SET quote = "Stay close to any sounds that make you glad you are alive." -- Hafiz WHERE id = 15;
-- UPDATE students SET quote = "Two roads diverged in a wood, and I— I took the one less traveled by,                         and that has made all the difference." - Robert Frost WHERE id = 16;
-- UPDATE students SET quote = "I have no special talent. I am only passionately curious." -- Albert Einstein WHERE id = 17;
-- UPDATE students SET quote = "Glory is fleeting, but obscurity is forever."- Napoleon Bonaparte (1769-1821) WHERE id = 18;
-- UPDATE students SET quote = "Make it work, make it right, make it fast." -- Kent Beck WHERE id = 19;
-- UPDATE students SET quote = "All life is an experiment." -- Ralph Waldo Emerson. WHERE id = 20;
-- UPDATE students SET quote = "The net-net is bad for fish" -- JMR WHERE id = 21;
-- UPDATE students SET quote = "Experience is simply the name we give our mistakes." ~Oscar Wilde WHERE id = 22;
-- UPDATE students SET quote = "It behooves every man to remember that the work of the critic is of altogether secondary importance, and that in the end, progress is accomplished by the man who does things." --Theodore Roosevelt WHERE id = 23;
-- UPDATE students SET quote = " Today I am happy. Are you?" -- Elsa Dees, 5 WHERE id = 24;
-- UPDATE students SET quote = "Cities have the capability of providing something for everybody, only because, and only when, they are created by everybody." -- Jane Jacobs, The Death and Life of Great American Cities WHERE id = 25;
-- UPDATE students SET quote = Learning to Speak Computer WHERE id = 26;
-- UPDATE students SET quote =  WHERE id = 27;
-- UPDATE students SET quote = ""Neither from itself nor from another                     Nor from both,                    Nor without a cause,                    Does anything whatever, anywhere arise."                    — -Nagarjuna, buddhist priest and philosopher WHERE id = 28;
-- UPDATE students SET quote = "Without visibility, there can be no debugging." -- Dr. Gordon Novak WHERE id = 29;
-- UPDATE students SET quote = "It's kind of fun to do the impossible." - Walt Disney WHERE id = 30;
-- UPDATE students SET quote = "Doubt is not a pleasant condition, but certainty is an absurd one" - Voltaire WHERE id = 31;
-- UPDATE students SET quote = “Adopt the pace of nature: her secret is patience” — Ralph Waldo Emerson WHERE id = 32;
-- UPDATE students SET quote = "A human is a system for converting dust billions of years ago into dust billions of years from now via a roundabout process which involves checking email a lot." WHERE id = 33;
UPDATE students SET biography = "I was born and raised up in Shanghai and came to US for college. I stuided and worked in Sillicon Valley, Long Island, Rhode Island, and now happily study and work in Manhattan." WHERE id = 1;
UPDATE students SET biography = "I grew up in and around NY (Gowanus, Flatbush, New Paltz), and majored in Mathematics at Oberlin College. I moved out west pursuing a music career and lived in Oakland for a year before landing in Seattle for 10+ years. Now I'm re-exploring math and learning to program." WHERE id = 2;
UPDATE students SET biography = "I'm a painter and an aspiring programmer,I love art theory and most things conceptual." WHERE id = 3;
UPDATE students SET biography = "I was born in LA and I lived in Ohio until I was 12. I then moved to Cyprus in Europe where I attended middle and high school. After a year of mandatory military service I went to London to study Electrical Engineering. I loved building electronics but I also loved programming the things I built and connecting them to the outside world. I decided I wanted to become a web developer and enrolled in the flatiron school." WHERE id = 4;
UPDATE students SET biography = "I used to be scared of dogs. Then I saw one take a piss on the street corner. In front of everyone. I'm still scared of dogs, but now I think they're kind of gross." WHERE id = 5;
UPDATE students SET biography = "Linus TorvaldsZed ShawDHH" WHERE id = 6;
UPDATE students SET biography = "After traversing through the lands of financial Excel spreadsheets, I'm now learning to navigate the open sea as a web developer." WHERE id = 7;
UPDATE students SET biography = "Mike is a member of the Flatiron School's Fall 2013 class.  Prior to entering the coding world, he produced television for Warner Bros and HBO in NYC.  He has also run corporate PR accounts at MWW Group, a top-five global independant PR firm.  Mike is a California native and Brooklyn resident.  Go Nets." WHERE id = 8;
UPDATE students SET biography = "Neophile, technophile, thaasophobe. An ENFP rural Maine transplant who likes yoga, jazz, and ramen." WHERE id = 9;
UPDATE students SET biography = "Ohio native, Duke 2010 grad, worked in NYC finance for 3 years before leaving to become a Ruby padawan @flatironschool." WHERE id = 10;
UPDATE students SET biography = "I'm originally from Atlanta, but have split my adult life between Boston and New York City. I previously worked in Project Management at a web development agency and am now an aspiring rails developer at the Flatiron school." WHERE id = 11;
UPDATE students SET biography = "Aspiring web developer, enrolled at the flatiron school." WHERE id = 12;
UPDATE students SET biography = "I studied anthropology in college and still keep it close in my heart. I am fascinated in the weird and wonderful ways we use machines to be social creatures. My interests include food exploration, stories, travel, Brooklyn, and animals." WHERE id = 13;
UPDATE students SET biography = "Aspiring to help create the world we live in." WHERE id = 14;
UPDATE students SET biography = "Once a teacher, now a coder. I enjoy biking, swimming, cooking, making music (violin, viola and voice)." WHERE id = 15;
UPDATE students SET biography = "I am a recent transplant to NYC from Washington, DC, where I worked in renewable energy project development for                  two years.  I'm currently a Rubywan at the Flatiron School, and I am planning to immerse myself into web development." WHERE id = 16;
UPDATE students SET biography = "I grew up in NJ playing a lot of music. In college, I studied music licensing and copyright. Before Flatiron, I was a marketer at a music/tech startup. In my spare time I enjoy solving puzzles, reading, cooking, watching movies, and hiking." WHERE id = 17;
UPDATE students SET biography = "James embarks on his journey to follow his passion to build great websites and apps. James hopes to level up his skills in computer programming at the Flatiron School." WHERE id = 18;
UPDATE students SET biography = "After growing up in the quiet suburbs of Minneapolis, I headed to big New York City for college. After an urban Ivy League education, I sought adventure in the field as an officer in the Marine Corps. Now I'm taking aim at something else -- building awesome things with code." WHERE id = 19;
UPDATE students SET biography = "Being a web developer has been on the back of my mind for awhile now, so I'm thrilled to be learning full stack development at Flatiron. When I'm not coding, you can find me playing ultimate frisbee." WHERE id = 20;
UPDATE students SET biography = "Worked in advertising for years as an account planner. Changed careers to data analysis. Looking to get more useful." WHERE id = 21;
UPDATE students SET biography = "I'm an erstwhile visual effects artist, technical writer, animator, fantasy writer, and a huge tabletop gaming nerd. I've been coding sporadically since I was in middle school, and I'm ecstatic to be coming back to it." WHERE id = 22;
UPDATE students SET biography = "I majored in English at Duke University, but I probably should have known in 6th grade after writing a board game in Pascal for a book report assignment that I'd one day be a programmer. It took me until now to jump on it. Better late than never though, right?" WHERE id = 23;
UPDATE students SET biography = "Grew up in Minnesota, married mom of two girls, Juliana 8, Elsa 5." WHERE id = 24;
UPDATE students SET biography = "Before learning to program, my path took me through the design, urban planning, policy, and environmental worlds. I've spent time in the trenches dealing with really big problems facing our world. I'm learning to program so I will be more equipt to solve them." WHERE id = 25;
UPDATE students SET biography = "I was born and raised in the Philadelphia, PA area. I enjoy outdoor sports and generally enjoy geek culture." WHERE id = 26;
UPDATE students SET biography = "World traveler, food eater, bike rider, music listener. Passionately curious eternal stuent. Aspiring web developer." WHERE id = 27;
UPDATE students SET biography = "Hailing from the lakes of Minnesota - with pit stops in San Francisco, Barcelona, Lucca, Bamako, Colorado, and DC - and after 8 years of writing, editing and art/design, I have a newfound passion for web development and design. Enter Flatiron School of Coding. :)" WHERE id = 28;
UPDATE students SET biography = "I've done a little bit of everything from coding intranet apps to tech support to hardware setups. I'm excited by the prospect of empowering small businesses with web apps." WHERE id = 29;
UPDATE students SET biography = "I speak Spanish and run a profitable iOS product company. But now I'm learning to be a software developer and make products on my own. I love tech." WHERE id = 30;
UPDATE students SET biography = "There's poetry in modeling data in a way that                   is both useful to humans and understandable by machines.                   I'm primarily interested in the art and logic of creation and                   the result of smashing created objects and ideas into the real                   world of particles, proteins and people." WHERE id = 31;
UPDATE students SET biography = "Grew up in Bucks County Pennsylvania. Played and coached lacrosse internationally. Professional background in real estate private equity. Currently attending Flatiron and couldn’t be happier." WHERE id = 32;
UPDATE students SET biography = "I could never put aside my LEGO mindstorm for more than two weeks, I am obsessed with drones and sentry guns, I watch unhealthy amounts of math related videos on Youtube and when I see my code running smoothy-smooth I experience inappropriate amounts of joy.  I ♡ Ruby, RoR & everything open source. I am super curious to see how 3Dprinting will change our environment as it gets more and more accessible." WHERE id = 33;
UPDATE students SET twitter = "https://twitter.com/vivian__zhang" WHERE id = 1;
UPDATE students SET twitter = "https://twitter.com/" WHERE id = 2;
UPDATE students SET twitter = "https://twitter.com/kyleshike" WHERE id = 3;
UPDATE students SET twitter = "https://twitter.com/mpolycarpou" WHERE id = 4;
UPDATE students SET twitter = "https://twitter.com/saronyitbarek" WHERE id = 5;
UPDATE students SET twitter = "https://twitter.com/davidhenrybella" WHERE id = 6;
UPDATE students SET twitter = "https://twitter.com/gregeng" WHERE id = 7;
UPDATE students SET twitter = "https://twitter.com/mikespangler" WHERE id = 8;
UPDATE students SET twitter = "https://twitter.com/emilyxxie" WHERE id = 9;
UPDATE students SET twitter = "https://twitter.com/mecampbellsoup" WHERE id = 10;
UPDATE students SET twitter = "http://www.twitter.com/peontiffany" WHERE id = 11;
UPDATE students SET twitter = "https://twitter.com/TheRealChiu" WHERE id = 12;
UPDATE students SET twitter = "https://twitter.com/ahimmelstoss" WHERE id = 13;
UPDATE students SET twitter = "https://twitter.com/Creeefs" WHERE id = 14;
UPDATE students SET twitter = "https://twitter.com/" WHERE id = 15;
UPDATE students SET twitter = "https://twitter.com/irmiller22" WHERE id = 16;
UPDATE students SET twitter = "https://twitter.com/iris_lee" WHERE id = 17;
UPDATE students SET twitter = "https://twitter.com/jamesjtong" WHERE id = 18;
UPDATE students SET twitter = "https://twitter.com/jnoconor" WHERE id = 19;
UPDATE students SET twitter = "https://twitter.com/jronigr" WHERE id = 20;
UPDATE students SET twitter = "https://twitter.com/richardsonjm" WHERE id = 21;
UPDATE students SET twitter = "https://twitter.com/j_scag_" WHERE id = 22;
UPDATE students SET twitter = "https://twitter.com/loganhasson" WHERE id = 23;
UPDATE students SET twitter = "https://twitter.com/margeleedees2" WHERE id = 24;
UPDATE students SET twitter = "https://twitter.com/rhoyem" WHERE id = 25;
UPDATE students SET twitter = "https://twitter.com/SamuelDOwens" WHERE id = 26;
UPDATE students SET twitter = "https://twitter.com/scottluptowski" WHERE id = 27;
UPDATE students SET twitter = "https://twitter.com/" WHERE id = 28;
UPDATE students SET twitter = "https://twitter.com/theevo" WHERE id = 29;
UPDATE students SET twitter = "https://twitter.com/trevmckendrick" WHERE id = 30;
UPDATE students SET twitter = "https://twitter.com/vinneycavallo" WHERE id = 31;
UPDATE students SET twitter = "https://twitter.com/" WHERE id = 32;
UPDATE students SET twitter = "https://twitter.com/EdinaVath" WHERE id = 33;
UPDATE students SET linkedin = "http://www.linkedin.com/in/shangxuanzhang" WHERE id = 1;
UPDATE students SET linkedin = "http://www.linkedin.com/" WHERE id = 2;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/kyle-shike/67/a83/4b" WHERE id = 3;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/michael-polycarpou/43/869/1b5" WHERE id = 4;
UPDATE students SET linkedin = "http://www.linkedin.com/in/saronyitbarek" WHERE id = 5;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/david-bella/56/a14/882" WHERE id = 6;
UPDATE students SET linkedin = "http://www.linkedin.com/in/gregeng" WHERE id = 7;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/mike-spangler/10/3a0/788/" WHERE id = 8;
UPDATE students SET linkedin = "http://www.linkedin.com/in/xieemily" WHERE id = 9;
UPDATE students SET linkedin = "http://www.linkedin.com/in/mecampbellsoup" WHERE id = 10;
UPDATE students SET linkedin = "http:www.linkedin.com/pub/tiffany-peón/13/95a/a27/" WHERE id = 11;
UPDATE students SET linkedin = "http://www.linkedin.com/profile/view?id=160096053&trk=nav_responsive_tab_profile_pic" WHERE id = 12;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/amanda-himmelstoss/23/5/101" WHERE id = 13;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/christopher-lee/9/558/483" WHERE id = 14;
UPDATE students SET linkedin = "http://www.linkedin.com/" WHERE id = 15;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/ian-miller/2a/834/201" WHERE id = 16;
UPDATE students SET linkedin = "http://www.linkedin.com/in/irislee1" WHERE id = 17;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/james-tong/2b/7b9/78a" WHERE id = 18;
UPDATE students SET linkedin = "http://www.linkedin.com/in/jnoconor" WHERE id = 19;
UPDATE students SET linkedin = "http://www.linkedin.com/in/jronigr" WHERE id = 20;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/john-richardson/4/1b/267/" WHERE id = 21;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/josh-scaglione/7a/85a/188" WHERE id = 22;
UPDATE students SET linkedin = "http://www.linkedin.com/pub/logan-hasson/1b/a11/92" WHERE id = 23;
UPDATE students SET linkedin = "http://www.linkedin.com/margaretleedees2" WHERE id = 24;
UPDATE students SET linkedin = "www.linkedin.com/in/rosiehoyem/" WHERE id = 25;
UPDATE students SET linkedin = "www.linkedin.com/pub/samuel-owens/7a/661/23a/" WHERE id = 26;
UPDATE students SET linkedin = "http://www.linkedin.com/in/scottluptowski" WHERE id = 27;
UPDATE students SET linkedin = "http://www.linkedin.com/" WHERE id = 28;
UPDATE students SET linkedin = "http://www.linkedin.com/in/theovora" WHERE id = 29;
UPDATE students SET linkedin = "http://www.linkedin.com/in/trevormckendrick" WHERE id = 30;
UPDATE students SET linkedin = "http://linkedin.com/pub/vinney-cavallo/21/52b/233" WHERE id = 31;
UPDATE students SET linkedin = "http://www.linkedin.com/" WHERE id = 32;
UPDATE students SET linkedin = "http://www.linkedin.com/EdinaVath" WHERE id = 33;
UPDATE students SET blog = "https://www.facebook.com/shangxuan.zhang" WHERE id = 1;
UPDATE students SET blog = "#" WHERE id = 2;
UPDATE students SET blog = "http://kyleshike.github.io" WHERE id = 3;
UPDATE students SET blog = "https://www.michaelpolycarpou.com" WHERE id = 4;
UPDATE students SET blog = "#" WHERE id = 5;
UPDATE students SET blog = "http://www.davidbella.com" WHERE id = 6;
UPDATE students SET blog = "http://gregeng.github.io/" WHERE id = 7;
UPDATE students SET blog = "#" WHERE id = 8;
UPDATE students SET blog = "#" WHERE id = 9;
UPDATE students SET blog = "#" WHERE id = 10;
UPDATE students SET blog = "#" WHERE id = 11;
UPDATE students SET blog = "#" WHERE id = 12;
UPDATE students SET blog = "http://ahimmelstoss.github.io" WHERE id = 13;
UPDATE students SET blog = "#" WHERE id = 14;
UPDATE students SET blog = "#" WHERE id = 15;
UPDATE students SET blog = "http://irmiller22.github.io/" WHERE id = 16;
UPDATE students SET blog = "http://irislee.github.io/" WHERE id = 17;
UPDATE students SET blog = "#" WHERE id = 18;
UPDATE students SET blog = "http://jnoconor.github.io/atom.xml" WHERE id = 19;
UPDATE students SET blog = "#" WHERE id = 20;
UPDATE students SET blog = "#" WHERE id = 21;
UPDATE students SET blog = "http://j-scag.github.io" WHERE id = 22;
UPDATE students SET blog = "#" WHERE id = 23;
UPDATE students SET blog = "#" WHERE id = 24;
UPDATE students SET blog = "http://rosiehoyem.github.io/" WHERE id = 25;
UPDATE students SET blog = "feed:https://news.ycombinator.com/rss" WHERE id = 26;
UPDATE students SET blog = "#" WHERE id = 27;
UPDATE students SET blog = "#" WHERE id = 28;
UPDATE students SET blog = "http://theevo.github.io/atom.xml" WHERE id = 29;
UPDATE students SET blog = "http://trevormckendrick.com" WHERE id = 30;
UPDATE students SET blog = "#" WHERE id = 31;
UPDATE students SET blog = "#" WHERE id = 32;
UPDATE students SET blog = "#" WHERE id = 33;
UPDATE students SET github = "https://github.com/casunlight" WHERE id = 1;
UPDATE students SET github = "https://github.com/" WHERE id = 2;
UPDATE students SET github = "https://github.com/kyleshike" WHERE id = 3;
UPDATE students SET github = "https://github.com/polycarpou" WHERE id = 4;
UPDATE students SET github = "https://github.com/sarony" WHERE id = 5;
UPDATE students SET github = "https://github.com/davidbella" WHERE id = 6;
UPDATE students SET github = "http://github.com/gregeng" WHERE id = 7;
UPDATE students SET github = "https://github.com/mikespangler" WHERE id = 8;
UPDATE students SET github = "https://github.com/emilyxxie" WHERE id = 9;
UPDATE students SET github = "https://github.com/mecampbellsoup" WHERE id = 10;
UPDATE students SET github = "http://github.com/tiffanypeon" WHERE id = 11;
UPDATE students SET github = "https://github.com/AYC726" WHERE id = 12;
UPDATE students SET github = "https://github.com/ahimmelstoss" WHERE id = 13;
UPDATE students SET github = "https://github.com/Clee681" WHERE id = 14;
UPDATE students SET github = "https://github.com/" WHERE id = 15;
UPDATE students SET github = "https://github.com/irmiller22" WHERE id = 16;
UPDATE students SET github = "https://github.com/irislee" WHERE id = 17;
UPDATE students SET github = "https://github.com/jamesjtong" WHERE id = 18;
UPDATE students SET github = "https://github.com/jnoconor" WHERE id = 19;
UPDATE students SET github = "https://github.com/jronigr" WHERE id = 20;
UPDATE students SET github = "https://github.com/richardsonjm" WHERE id = 21;
UPDATE students SET github = "https://github.com/J-Scag" WHERE id = 22;
UPDATE students SET github = "https://github.com/loganhasson" WHERE id = 23;
UPDATE students SET github = "https://github.com/margaretleedees2" WHERE id = 24;
UPDATE students SET github = "https://github.com/rosiehoyem" WHERE id = 25;
UPDATE students SET github = "https://github.com/samueldowens" WHERE id = 26;
UPDATE students SET github = "https://github.com/scottluptowski" WHERE id = 27;
UPDATE students SET github = "https://github.com/" WHERE id = 28;
UPDATE students SET github = "https://github.com/theevo" WHERE id = 29;
UPDATE students SET github = "https://github.com/TrevMcKendrick" WHERE id = 30;
UPDATE students SET github = "https://github.com/vcavallo" WHERE id = 31;
UPDATE students SET github = "https://github.com/PHJ45" WHERE id = 32;
UPDATE students SET github = "https://github.com/EdinaVath" WHERE id = 33;
